2 inputs added, states added
Kszalank/Currency-Converter pull request #21
Opened 2023-03-08 19:32 UTC by Kszalank

Closes #9

2023-03-15 19:36 UTC, mecies requested changes
The logic is all good 👏 
I left some stylistic comments

2023-03-15 19:36 UTC, mecies commented on src/components/Selector.jsx
Please call this file Select instead of Selector, I haven't noticed before 😂

2023-03-15 19:36 UTC, mecies commented on src/components/Selector.jsx
> +    <select onChange={onChange} value={value} className="selector">
Same as the file name
```suggestion 
    <select onChange={onChange} value={value} className="select">
```

2023-03-15 19:36 UTC, mecies commented on src/styles/Input.scss
> +}
```suggestion
.input {
  border-radius: 5px;
  margin: 5px;
}

```

2023-03-15 19:36 UTC, mecies commented on src/styles/Selector.scss
> +}
```suggestion
.select {
  border-radius: 5px;
  margin: 5px;  
}
```

2023-03-15 19:36 UTC, mecies commented on src/styles/Selector.scss
Please rename this file to Select too

2023-03-16 15:09 UTC, Kszalank commented on src/components/Selector.jsx
done :D

2023-03-16 15:10 UTC, Kszalank commented on src/components/Selector.jsx
> +    <select onChange={onChange} value={value} className="selector">
done :)

2023-03-16 15:13 UTC, Kszalank commented on src/styles/Selector.scss
> +}
done

2023-03-16 15:13 UTC, Kszalank commented on src/styles/Selector.scss
done

2023-03-16 15:13 UTC, Kszalank commented on src/styles/Input.scss
> +}
done

2023-03-16 17:35 UTC, mecies approved these changes
Looks good to me

2023-03-16 17:35 UTC, mecies commented on src/styles/Select.scss
> +}
Conventionally you should leave a space between class name and the bracket
```suggestion
.select {
    border-radius: 5px;
    margin: 5px;
}
```

2023-03-16 17:35 UTC, mecies commented on src/styles/Input.scss
> +.input{
```suggestion
.input {
```

2023-03-18 20:25 UTC, merged